name: duckietown-enhanced-tier1
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # Python version - compatible with modern packages
  - python=3.10

  # Core PyTorch stack with CUDA 11.8 (no conflicts)
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8

  # Core scientific computing (relaxed versions)
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - opencv

  # RL stack - Gymnasium compatible (no gym conflicts)
  - tensorboard

  # Development and testing
  - pytest
  - pytest-cov
  - black
  - flake8

  # Jupyter and visualization
  - jupyter
  - jupyterlab
  - ipywidgets
  - plotly

  # System utilities
  - psutil
  - tqdm
  - pyyaml
  - click
  - requests

  # Image processing
  - imageio
  - scikit-image

  # Git and pip
  - git
  - pip

  # Additional dependencies via pip (WSL-optimized)
  - pip:
    # YOLO v5 and Ultralytics (latest stable)
    - ultralytics>=8.0.0
    
    # Modern RL stack - Gymnasium (SB3 v2 compatible)
    - gymnasium>=0.29.0
    - shimmy>=1.2.0
    - stable-baselines3>=2.0.0
    
    # gym-duckietown (specific version)
    - gym-duckietown==6.0.25
    
    # Ray RLLib (compatible with Gymnasium)
    - "ray[rllib]>=2.5.0"
    
    # Enhanced logging and monitoring
    - wandb
    - mlflow
    - tensorboardX
    
    # Image and video processing
    - imageio-ffmpeg
    - av
    
    # Additional computer vision
    - albumentations
    - imgaug
    
    # Performance monitoring
    - memory-profiler
    - line-profiler
    
    # Configuration management
    - hydra-core
    - omegaconf
    
    # Additional utilities
    - rich
    - typer
    - loguru
    
    # Testing utilities
    - pytest-xdist
    - pytest-benchmark
    - pytest-mock
    
    # Data processing
    - h5py
    - zarr
    
    # Networking and API
    - fastapi
    - uvicorn
    - websockets
    
    # Additional visualization
    - bokeh
    - altair
    
    # Development tools
    - pre-commit
    
    # ROS dependencies (for robot deployment)
    - rospkg
    - catkin-pkg
    - empy