# Evaluation System Integration Configuration
# Configuration for final evaluation system integration testing

integration_tests:
  # Test execution settings
  timeout_per_test: 300  # seconds
  memory_limit_mb: 2000
  concurrent_tests: 2
  
  # Test categories to run
  test_categories:
    - ultimate_champion_integration
    - master_orchestrator_integration
    - continuous_training_integration
    - model_evaluation_pipeline
    - all_evaluation_suites
    - statistical_analysis
    - failure_analysis
    - robustness_analysis
    - champion_selection
    - report_generation
    - artifact_management
    - memory_optimization
    - concurrent_performance
    - large_scale_performance

validation:
  # Performance thresholds
  performance_threshold_multiplier: 1.2
  memory_efficiency_threshold: 0.8
  accuracy_tolerance: 0.02
  
  # Success criteria
  min_test_success_rate: 0.9
  min_requirements_success_rate: 0.9
  max_memory_per_test_mb: 100
  min_concurrent_efficiency: 0.7

evaluation:
  # Test evaluation settings
  test_episodes_per_suite: 20
  test_models_count: 3
  bootstrap_samples: 1000
  confidence_level: 0.95
  
  # Suite configuration
  test_suites:
    - base
    - hard_randomization
    - law_intersection
    - out_of_distribution
    - stress_adversarial
  
  # Seeds for reproducibility
  base_seed: 42
  seeds_per_suite: 5

training_integration:
  # Training integration settings
  mock_training_episodes: 100
  evaluation_frequency: 50
  checkpoint_interval: 25
  
  # Model types to test
  model_types:
    - ultimate_champion
    - continuous_checkpoint
    - master_orchestrator_champion
    - validation_model
    - pipeline_test

performance_benchmarks:
  # Performance targets
  models_per_second: 50
  tasks_per_second: 100
  memory_per_episode_mb: 0.05
  memory_per_model_mb: 1.0
  max_memory_increase_mb: 500
  
  # Scalability targets
  max_concurrent_evaluations: 4
  large_scale_model_count: 20
  batch_processing_efficiency: 0.8

system_requirements:
  # System resource requirements
  min_available_memory_gb: 2.0
  min_disk_space_gb: 1.0
  max_cpu_usage_percent: 80
  
  # Component requirements
  required_components:
    - evaluation_orchestrator
    - suite_manager
    - metrics_calculator
    - statistical_analyzer
    - failure_analyzer
    - robustness_analyzer
    - champion_selector
    - report_generator
    - artifact_manager

logging:
  # Logging configuration
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  
  # Log files
  integration_log: 'logs/evaluation_integration/integration.log'
  performance_log: 'logs/evaluation_integration/performance.log'
  
  # Log retention
  max_log_files: 10
  max_log_size_mb: 100

artifacts:
  # Artifact management
  results_dir: 'logs/evaluation_integration'
  save_intermediate_results: true
  compress_artifacts: true
  
  # Cleanup settings
  cleanup_on_success: false
  cleanup_on_failure: false
  max_artifact_age_days: 30

reproducibility:
  # Reproducibility settings
  fix_random_seeds: true
  log_environment_info: true
  save_configuration: true
  
  # Version tracking
  track_git_commit: true
  track_dependencies: true
  track_system_info: true