# Research Evaluation Configuration Template
# High-rigor configuration optimized for research and publication

# Global evaluation settings
parallel_evaluation: true
max_parallel_workers: 6
evaluation_timeout_hours: 48.0

# Evaluation suites
suites:
  base:
    enabled: true
    seeds_per_map: 100
    maps:
      - loop_empty
      - small_loop
      - zigzag_dists
      - straight_road
    policy_modes:
      - deterministic
      - stochastic
    timeout_steps: 2000
    environmental_noise: 0.0
    traffic_density: 0.0
    lighting_variation: 0.0
    texture_variation: 0.0
    camera_noise: 0.0
    friction_variation: 0.0

  robustness:
    enabled: true
    seeds_per_map: 50
    maps:
      - loop_empty
      - small_loop
      - zigzag_dists
    policy_modes:
      - deterministic
      - stochastic
    timeout_steps: 2000
    environmental_noise: 0.5
    traffic_density: 0.1
    lighting_variation: 0.3
    texture_variation: 0.3
    camera_noise: 0.1
    friction_variation: 0.15

  generalization:
    enabled: true
    seeds_per_map: 75
    maps:
      - udem1
      - regress_4way_adam
      - ETHZ_autolab_technical_track
    policy_modes:
      - deterministic
      - stochastic
    timeout_steps: 2500
    environmental_noise: 0.3
    traffic_density: 0.2
    lighting_variation: 0.2
    texture_variation: 0.2
    camera_noise: 0.1
    friction_variation: 0.1

  stress:
    enabled: true
    seeds_per_map: 30
    maps:
      - loop_empty
      - small_loop
      - zigzag_dists
    policy_modes:
      - deterministic
    timeout_steps: 1500
    environmental_noise: 0.9
    traffic_density: 0.6
    lighting_variation: 0.8
    texture_variation: 0.8
    camera_noise: 0.6
    friction_variation: 0.4

# Metrics configuration
metrics:
  compute_confidence_intervals: true
  confidence_level: 0.95
  bootstrap_resamples: 20000
  min_episodes_for_ci: 20
  
  # Composite score weights (must sum to 1.0)
  success_rate_weight: 0.45
  reward_weight: 0.25
  episode_length_weight: 0.10
  lateral_deviation_weight: 0.08
  heading_error_weight: 0.06
  smoothness_weight: 0.06
  
  normalization_scope: per_map_suite
  use_composite_score: true

# Statistical analysis
statistical:
  significance_level: 0.01  # More stringent for research
  multiple_comparison_correction: benjamini_hochberg
  min_effect_size: 0.05  # Smaller effect sizes for research
  paired_tests: true
  use_parametric_tests: false
  bootstrap_comparisons: true

# Failure analysis
failure_analysis:
  enabled: true
  record_failure_videos: true
  max_failure_videos: 50
  generate_heatmaps: true
  save_episode_traces: true
  stuck_threshold_steps: 100
  oscillation_threshold: 0.3  # More sensitive
  overspeed_threshold: 1.8

# Robustness analysis
robustness:
  enabled: true
  parameter_sweeps:
    lighting_intensity: [0.3, 0.5, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.5, 1.7]
    texture_domain: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    camera_pitch: [-0.3, -0.2, -0.1, -0.05, 0.0, 0.05, 0.1, 0.2, 0.3]
    camera_roll: [-0.2, -0.1, -0.05, 0.0, 0.05, 0.1, 0.2]
    friction_coefficient: [0.4, 0.6, 0.8, 0.9, 1.0, 1.1, 1.2, 1.4, 1.6]
    traffic_density: [0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
    wheel_noise: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  min_success_rate_threshold: 0.80
  sensitivity_threshold: 0.05  # More sensitive threshold

# Champion selection
champion_selection:
  enabled: true
  min_maps_passing: 0.95  # Very high standard
  min_success_rate: 0.80
  max_regression_threshold: 0.02  # Very low tolerance for regression
  max_smoothness_increase: 0.10
  pareto_axes:
    - [success_rate, -lateral_deviation, -smoothness]
    - [success_rate, -heading_error, -smoothness]

# Artifacts and outputs
artifacts:
  output_directory: evaluation_results_research
  keep_top_k_models: 10
  export_csv: true
  export_json: true
  export_plots: true
  export_videos: true
  compress_artifacts: true
  cleanup_intermediate: false  # Keep all data for research
  max_artifact_age_days: 365  # Keep for a year

# Reproducibility (maximum rigor)
reproducibility:
  fix_seed_list: true
  seed_base: 42
  cudnn_deterministic: true
  log_git_sha: true
  log_environment_info: true
  track_model_versions: true
  track_config_versions: true